### ISSUE TITLE
Turn Penalties

### ISSUE THREAD

**Issue by RegularnaMatrica** [UrbanAnalyst/dodgr#305]
I have questions about turn penalties. I've read through several posts but didn't manage to find answer, sorry if this was already answerd. I create dodgr graph using `turn_penalty=TRUE` as following:

```
  response <- query_area %>%
    osmdata::opq() %>%
    osmdata::add_osm_feature(
      key = "highway",
      value = road_types
    ) %>%
    osmdata::osmdata_sc()
  response <- osmdata::trim_osmdata(response, sf::st_coordinates(query_area))
  
  full_graph <- dodgr::weight_streetnet(
    response, 
    wt_profile = "motorcar",
    turn_penalty = TRUE,
    keep_cols = c("access", "oneway" ,"maxspeed")
  )
```

I use `full_graph` to create paths with certain properties. I've notice that 'immediate' direction changes can happen that are not allowed according to the traffic regulations as seen on image below.

<img width="295" height="277" alt="Image" src="https://github.com/user-attachments/assets/4d493758-af1f-468a-9385-bf2799234abf" />

These are edges that start at middle node `2376664325`:

```
     .vx0        .vx1      edge_  .vx0_x   .vx0_y   .vx1_x   .vx1_y         d   object_ bicycle   foot highway oneway_bicycle  lanes
       <char>      <char>     <char>   <num>    <num>    <num>    <num>     <num>    <char>  <char> <char>  <char>         <lgcl> <char>
1: 2376664325 11649944748 2786HI3dBn 16.3563 46.31971 16.35615 46.31956  20.40856 229027623    <NA>   <NA> primary          FALSE      1
2: 2376664325  2376675186 vrSppkNwEv 16.3563 46.31971 16.35694 46.32051 102.22134  40818992    <NA>   <NA> primary          FALSE      2
   junction access d_weighted      time time_weighted component
     <char> <char>      <num>     <num>         <num>     <int>
1:     <NA>   <NA>   22.67618 0.9183853      1.020428         1
2:     <NA>   <NA>  113.57927 4.5999604      5.111067         1
```

It took option that has lower weighted distance/duration, but that option goes against traffic regulations.

Questions:

1. How are turn penalties applied. If it is according to the weight in the profile, shoudn't not allowed turns be multipled by 7.5?
2. Is it possible to remove edges that are not according to the traffic regulations?

**Comment by mpadge** [comment]
Easy answer first:

> Do you think it is possible to use `dodgr` to iteratively create drivable routes?

Sure, that should definitely be possible.

> I don't fully understand how `weight_streetnet` process the input (ex. are nodes with restrictions mapped to multiple nodes?) or how `dodgr_paths` works (in the desciption it says it uses some additional data in temporary cache). Do you think it is possible to use `dodgr` to iteratively create drivable routes?

The best description of the process of creating/modifying junctions to reflect turn restrictions is in https://urbananalyst.github.io/dodgr/articles/times.html#the-weight_streetnet-function. The initial specifications are all contained within the `sc`-class data passed to `weight_streetnet()`. If you inspect those data, you'll see they do include quite a few turn restrictions:

``` r
library (dodgr)
bb <- c (16.3, 46.28, 16.5, 46.38)
net_sc <- dodgr_streetnet_sc (bb, expand = 0)
net_sc$relation_properties
#> # A tibble: 254 × 3
#>    relation_ key         value       
#>    <chr>     <chr>       <chr>       
#>  1 3941827   restriction no_left_turn
#>  2 3941827   type        restriction 
#>  3 4229151   restriction no_u_turn   
#>  4 4229151   type        restriction 
#>  5 4229152   restriction no_u_turn   
#>  6 4229152   type        restriction 
#>  7 4229153   restriction no_u_turn   
#>  8 4229153   type        restriction 
#>  9 4229154   restriction no_u_turn   
#> 10 4229154   type        restriction 
#> # ℹ 244 more rows
```

<sup>Created on 2025-08-28 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

The first of these, for example, is https://www.openstreetmap.org/relation/3941827, clearly showing how this restriction is specified in OSM. Your problem would be directly solved by updating the OSM data base to add an additional restriction for the problematic turn. You can see that there is currently no restriction there by looking at https://www.openstreetmap.org/way/365614606, and examining all relations of which that is part. There is no turn restriction, and so simply adding one to the OSM data would be the best and most immediate way to fix that. That would also help anybody and everybody who is going to use those data from that point on.

Alternatively, you could technically add the specified restriction within the `sc` object prior to passing it to `weight_streetnet()`.  You'd need to do something like:

- Create a new arbitrary relation ID
- Add 2 lines to `net_sc$relation_properties`, copying data from the example of 3941827
- Add 3 lines to `net_sc$relation_members` specifying the `from` and `to` ways, and the central node, again copying structures from other examples.

If you decide to go that way, start with `str(net_sc)` to understand the data representation of the `sc` object. Passing those modified `sc` data to `weight_streetnet` should reflect that newly created restriction.

**Comment by RegularnaMatrica** [comment]
Thanks for help and patience. I've gone through preprocessing steps and there was an error which discarded some of the relations that shouldn't be discarded. After generating few routes it seems that problem still exists. I think that following situation causes problems: doing extension when the end of current route is a node that has turn restriction, `dodgr_paths` does not know how it arrived to current end. One approach would be to forbid such nodes to ever be extension candidates.

I can't say that I fully understand preprocessing described in article you've linked, but it seems to me that preprocessing is not reflected directly at data.frame returned by `weight_streetnet` but rather by adding additional attributes containing turn restrictions.

Take following restriction: https://www.openstreetmap.org/relation/9887469. What I would like is for node 340019159 to be splitted into two nodes:

1st node: in neighbours: 7152731105  out neighbours: 3410602245, 340019158
2nd node: in neighbours: 3410602242 out neighbours: 7152731105

to reflect turn restrictions, but the data says it has 3 out neighbours (3410602245, 340019158, 7152731105):

```
pt <- c(16.484342, 46.284267)

fts <- c(
  "\"highway\"",
  "\"restriction\"",
  "\"access\"",
  "\"motorcar\"",
  "\"motor_vehicle\"",
  "\"vehicle\""
)

polygon <- sf::st_buffer(
  sf::st_sfc(sf::st_point(pt), crs = 4326), 
  dist = 100
)

xml <- osmdata::opq(polygon) %>%
  osmdata::add_osm_features(fts) %>%
  osmdata::osmdata_xml()

sc_obj <- osmdata::osmdata_sc(doc = xml)

full_graph <- dodgr::weight_streetnet(
  sc_obj, 
  wt_profile = "motorcar",
  turn_penalty = TRUE
)

full_graph %>%
  dplyr::filter(.vx0 == "340019159") %>%
  purrr::pluck(".vx1")
[1] "3410602245" "7152731105" "340019158"

full_graph %>%
  dodgr::dodgr_to_igraph() %>%
  igraph::neighbors(
    v = "340019159",
    mode = "out"
  )
3/63 vertices, named, from df55616:
[1] 3410602245 340019158  7152731105
```

Is it possible to use turn restriction attributes and dodgr graph to derive similar data.frame which would instead of node adjecency  describe edge adjacency taking in consideration turn restrictions?

**Comment by mpadge** [comment]
I haven't looked at the turn restriction implementations for so long, I forgot how and where they were actually imposed. I think my thought process was something like restrictions could only be effectively implemented when I knew what they'd be needed for, because different dodgr functions have to consider them differently. So current implementations (noting that "with_tp" = "with turn penalty", which also obeys restrictions) are:
https://github.com/UrbanAnalyst/dodgr/blob/f767eec2080863795cc574d7997dea53239e202d/R/dists.R#L172-L175
https://github.com/UrbanAnalyst/dodgr/blob/f767eec2080863795cc574d7997dea53239e202d/R/dists-nearest.R#L105-L108
https://github.com/UrbanAnalyst/dodgr/blob/f767eec2080863795cc574d7997dea53239e202d/R/flows.R#L170-L173
(alongside all other flow functions)
https://github.com/UrbanAnalyst/dodgr/blob/f767eec2080863795cc574d7997dea53239e202d/R/iso.R#L110-L113

That means that these functions and methods currently ignore turn restrictions:
https://github.com/UrbanAnalyst/dodgr/blob/f767eec2080863795cc574d7997dea53239e202d/R/dists-categorical.R#L148-L149
https://github.com/UrbanAnalyst/dodgr/blob/f767eec2080863795cc574d7997dea53239e202d/R/paths.R#L87-L94
plus https://github.com/UrbanAnalyst/dodgr/blob/main/R/centrality.R

This all needs to be reconciled and fixed.

**Comment by RegularnaMatrica** [comment]
That was fast, tnx for the effort. For my use-case it's important to impose turn restrictions. Do you think it is possible in 'processing' step  to achieve edge adjacency graph instead of node one? It should be possible to use data in `turn_restrictions_only` and `turn_restrictions_no` to filter out all unallowed turn restrictions.  Problem for doing it in current state is that graph returned by `weight_streetnet` does not contain OSM way information like these attributes do. Is it possible/meaningful to include way_from, way_to columns that would be OSM way ids?

**Comment by mpadge** [comment]
Thanks @RegularnaMatrica for continuing to push this issue. It's really helped to uncover and resolve bugs in how compound junctions are handled. This latest iteration has fixed another two bugs, which is great.

To answer your question: All graphs returned from all dodgr functions represent all information, and so potentially include connections which may be prohibited. Those prohibitions are handled in the code linked above, which is always called when the graphs are passed to whatever function they're being submitted to. You can nevertheless access those graph using the internal function, `create_compound_junctions()`. First create the standard graph:

``` r
library (dodgr)
dodgr_cache_off ()
bb <- c (16.3, 46.28, 16.5, 46.
net <- dodgr_streetnet_sc (bb, expand = 0, quiet = FALSE)
graph <- weight_streetnet (net, wt_profile = "motorcar", turn_penalty = TRUE)
nrow (graph)
#> [1] 31776
```

These are the data for the turn restriction https://www.openstreetmap.org/relation/3941827:

``` r
way_ids <- c ("296399434",  "296399432") # from -> to
node_id <- "2815182079"
```

These are the bits of that as represented in the graph:
``` r
dplyr::filter (graph, .vx0 == node_id | .vx1 == node_id) [, 1:9]
#> # A tibble: 4 × 9
#>   .vx0        .vx1       edge_      .vx0_x .vx0_y .vx1_x .vx1_y     d object_  
#>   <chr>       <chr>      <chr>       <dbl>  <dbl>  <dbl>  <dbl> <dbl> <chr>    
#> 1 2815182079  9825876224 LYVMfnTLv3   16.3   46.3   16.3   46.3 12.6  296399432
#> 2 10589543417 2815182079 DWE690s9dY   16.3   46.3   16.3   46.3 12.0  296399434
#> 3 486091258   2815182079 1lDHsvMjHL   16.3   46.3   16.3   46.3  9.92 365622182
#> 4 2815182079  486091258  QYOvgkRdXg   16.3   46.3   16.3   46.3  9.92 365622182
```

And there are four edges, representing the four possible ways of connecting (= in and out), and in both directions. The direct edges of the turn restriction are:

``` r
dplyr::filter (graph, (object_ %in% way_ids & (.vx0 == node_id | .vx1 == node_id))) |>
    dplyr::select (.vx0, .vx1, object_)
#> # A tibble: 2 × 3
#>   .vx0        .vx1       object_  
#>   <chr>       <chr>      <chr>    
#> 1 2815182079  9825876224 296399432
#> 2 10589543417 2815182079 296399434
```

And the second bit of that shows it's possible to turn from 296399434 to 296399432 via the central node 2815182079. The turn restriction needs to prevent those edges from connecting. And that's what the `create_compound_junction()` function does:

``` r
res <- dodgr:::create_compound_junctions (graph)
graph_compound <- res$graph
nrow (graph_compound)
#> [1] 34660
```

The graph has a lot more junctions, because each simple one which is prohibited then has to be replaced by "compound junctions" representing all possible connections from points either side of the junction. Then check whether that junction is present in the graph:

``` r
dplyr::filter (graph_compound, (object_ %in% way_ids & (.vx0 == node_id | .vx1 == node_id))) |>
    dplyr::select (.vx0, .vx1, object_)
#> # A tibble: 0 × 3
#> # ℹ 3 variables: .vx0 <chr>, .vx1 <chr>, object_ <chr>
```

And those edges have gone (even though other edges with the same OSM way IDs still exist). The junction vertex is still allowed to be there, just not in ways that connect it directly through the prohibited turn:

``` r
cols <- c (".vx0", ".vx1", "edge_", "object_")
g <- dplyr::filter (graph_compound, .vx0 == node_id | .vx1 == node_id)
g [, cols]
#> # A tibble: 2 × 4
#>   .vx0       .vx1       edge_      object_  
#>   <chr>      <chr>      <chr>      <chr>    
#> 1 486091258  2815182079 1lDHsvMjHL 365622182
#> 2 2815182079 486091258  QYOvgkRdXg 365622182
```

Finally, get all ways which connect to the node beyond the junction node (= 486091258, from above):

``` r
outer_node <- g$.vx0 [which (!g$.vx0 == node_id)]
dplyr::filter (graph_compound, .vx0 == outer_node | .vx1 == outer_node) [, cols]
#> # A tibble: 7 × 4
#>   .vx0        .vx1       edge_      object_            
#>   <chr>       <chr>      <chr>      <chr>              
#> 1 486091258   5481413345 95vw5RBYhl 40294541           
#> 2 3696274800  486091258  NP27dyEMjn 365622182          
#> 3 486091258   2815182079 1lDHsvMjHL 365622182          
#> 4 5481413345  486091258  cxAWNKNYwr 40294541           
#> 5 486091258   3696274800 ZLunmQJc33 365622182          
#> 6 2815182079  486091258  QYOvgkRdXg 365622182          
#> 7 10589543417 486091258  QYOvgkRdXg 296399434_365622182
```

And the last of those is the single compound junction which has replaced the direct (prohibited) connection in the full graph. Travel from the "from" way in https://www.openstreetmap.org/relation/3941827 (which is 296399434) is permitted as long is it does not connect with "to = 296399432". The compound junctions have updated `object_` values combining the `in` and `out` OSM way IDs, so that junction connects https://www.openstreetmap.org/way/296399434 directly to https://www.openstreetmap.org/way/365622182.

Finally, and but in general, you shouldn't need to directly access that information, as all calculations will always include it, and will appropriately respect any and all turn restrictions. And do it properly now, thanks to the bugs this has uncovered. Let me know if you've got any more questions.

**Comment by mpadge** [comment]
@RegularnaMatrica I'm going to close this now - thanks for all the input and incentive to improve the way dodgr deals with turn penalties. Please keep providing any further feedback at any time
